### ISSUE TITLE
new instruction proposal Zihintpause

### ISSUE THREAD

**Issue by simon5656** [riscv-software-src/riscv-config#39]
I wonder if new proposals like this new instruction should be added at this early stage to riscv-config
it is not in the ratified specs
and there seems no place from riscv.org that I can see its definition.
is it a real instruction or pseudo
will this instruction being in the device yaml affect anything - like selection/config of tests, test generators, simulators?
why has this instruction been singled out to be added?
what about all other proposed extensions.

thanks for any clarifications...

**Comment by neelgala** [comment]
Adding updates to riscv-config is part of the ratification process for an instruction/extension. I guess I should have waited for the official raitification announcement before merging the PR.

The changes made for this PR will not affect existing tools in anyway. They can however choose to do something extra with this if they like. 

@gfavor will probably be best to answer questions on the origin on this instruction

**Comment by allenjbaum** [comment]
I think it has been ratified now; it was a fast-track ratification. It is a hint instruction which (architecturally) acts like a NOP. So, this can probably be closed, though the question remains: at what point should instructions and features be added to the config schema?

**Comment by gfavor** [comment]
Yes, this was officially ratified at the beginning of the year.  There was even a public announcement about it as the first extension using the new fast-track process - along with quotes from Mark and me about the wonders of the fast-track process and the instruction itself.

**Comment by Imperas** [comment]
If it was ratified - surely it would be in on the RISCV.org specifications page?
https://riscv.org/technical/specifications/
Maybe somebody should get that page up to date if there are ratified specs not listed there?
In fact that page should only have ratified specs.
Maybe the working group chair of the ratified spec should ensure that that page gets updated.
Otherwise the ratified spec is just a secret and can not be of much interest if it is not publicised.
People should not be confused as to what the specs are ... there should be one home... https://riscv.org/technical/specifications/
and it should be up to date, comprehensive, and complete.
Simon

**Comment by gfavor** [comment]
I think this is an issue to bring up with the Unpriv IC.  I suspect, with all the various unpriv extensions happening this year, this gets into the mechanics of releasing new ratified Unpriv specs (of which I have no idea what are the intended mechanics).

As a side-note, the PAUSE Hint extension was quite publicly announced (i.e. in the RVI marketing sense).  I don't remember what was done announcement-wise within the RVI techncial community.

**Comment by neelgala** [comment]
Zihintpause is now supported in riscv-config and is ratified. Closing this for now
